# netlify.toml
# Este arquivo configura o comportamento do seu site no Netlify.

# Configurações de build
[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

# Configurações de funções
[functions]
  directory = "netlify/functions/"

# Redirecionamentos para rotas de API mais limpas
[[redirects]]
  from = "/api/get-motivation"
  to = "/.netlify/functions/get-motivation"
  status = 200

[[redirects]]
  from = "/api/get-training-tips"
  to = "/.netlify/functions/get-training-tips"
  status = 200

[[redirects]]
  from = "/api/generate-image-gemini"
  to = "/.netlify/functions/generate-image-gemini"
  status = 200

# Políticas de Segurança de Conteúdo (Content Security Policy - CSP) e outros cabeçalhos
# netlify.toml

# ... suas outras configurações ...

[[headers]]
  for = "/*" # Aplica-se a todas as rotas do seu site
  [headers.values]
    Content-Security-Policy = "default-src 'self' data:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://pagead2.googlesyndication.com https://www.highperformanceformat.com https://descendedlibrarian.com https://pl27203787.profitableratecpm.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://frasesmotivacionaisapi.com https://www.google-analytics.com https://api.cloudconvert.com https://us-east.storage.cloudconvert.com; frame-src 'self' https://googleads.g.doubleclick.net;"
    # Aqui é onde os URLs são adicionados corretamente.    # Outros cabeçalhos de segurança recomendados
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"